ZSH=$HOME/.oh-my-zsh
source ~/dotfiles/zsh-config/aliases.zsh
export PATH=~/.meteor/tools/latest/bin:$PATH
export EDITOR='vim'
ZSH_THEME="raj"
# my custom settings
plugins=(bundler capistrano debian gem git git-flow github git-remote-branch gitignore history rails rake rbenv ruby sudo meteor )

source $ZSH/oh-my-zsh.sh


# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

